Abstract Factory Design Pattern: Driver.cpp File Reference
Driver.cpp File Reference
#include "MazeGame.h"
#include "Maze.h"
#include "Singleton.h"
Functions
int main ()
Function Documentation
int main ()
Definition at line 5 of file Driver.cpp.
References MazeGame::CreateMaze(), FactoryInstance(), and Maze::Print().