Abstract Factory Design Pattern: Object Class Reference
Object Class Reference
#include <Object.h>
Inherited by MapSite, Maze, MazeFactory, MazeGame, ObjectArray, and ObjectLink.
Public Member Functions
Object (int pId=0)
virtual ~Object ()
virtual void Print (int indent=0)
Private Attributes
int Id
Detailed Description
Definition at line 6 of file Object.h.
Constructor & Destructor Documentation
Object::Object (int pId = 0)
Definition at line 3 of file Object.cpp.
References Id.
Object::~Object () [virtual]
Definition at line 7 of file Object.cpp.
Member Function Documentation
void Object::Print (int indent = 0) [virtual]
Reimplemented in BombedMazeFactory, BombedWall, Door, MapSite, Maze, MazeFactory, MazeGame, ObjectArray, ObjectLink, Room, and Wall.
Definition at line 10 of file Object.cpp.
References Id, and PrintIndent().
Referenced by ObjectLink::Print(), and ObjectArray::Print().
Member Data Documentation
int Object::Id [private]
Definition at line 13 of file Object.h.
Referenced by Object(), and Print().
The documentation for this class was generated from the following files:
Object.h
Object.cpp