Abstract Factory Design Pattern: ObjectArray Class Reference
ObjectArray Class Reference
#include <ObjectArray.h>
Inherits Object.
Public Member Functions
ObjectArray ()
virtual ~ObjectArray ()
void FreeArray ()
virtual class Object * GetAt (int pAt)
virtual class Object * PutAt (int pAt, class Object *pO, bool replace=true)
bool IsEmpty ()
virtual void Print (int indent=0)
Private Attributes
class ObjectLink * _first
Detailed Description
Definition at line 6 of file ObjectArray.h.
Constructor & Destructor Documentation
ObjectArray::ObjectArray ()
Definition at line 8 of file ObjectArray.cpp.
References _first.
ObjectArray::~ObjectArray () [virtual]
Definition at line 13 of file ObjectArray.cpp.
References _first, and ObjectLink::GetNext().
Member Function Documentation
void ObjectArray::FreeArray ()
Definition at line 24 of file ObjectArray.cpp.
References _first, ObjectLink::GetNext(), and ObjectLink::GetValue().
class Object * ObjectArray::GetAt (int pAt) [virtual]
Definition at line 38 of file ObjectArray.cpp.
References _first, ObjectLink::GetIndex(), ObjectLink::GetNext(), and ObjectLink::GetValue().
Referenced by Room::GetSide(), and Maze::RoomNo().
bool ObjectArray::IsEmpty ()
Definition at line 81 of file ObjectArray.cpp.
References _first.
Referenced by Print().
void ObjectArray::Print (int indent = 0) [virtual]
Reimplemented from Object.
Definition at line 85 of file ObjectArray.cpp.
References _first, ObjectLink::GetNext(), ObjectLink::GetValue(), IsEmpty(), Object::Print(), and PrintIndent().
Referenced by Room::Print(), and Maze::Print().
class Object * ObjectArray::PutAt (int pAt, class Object * pO, bool replace = true) [virtual]
Definition at line 51 of file ObjectArray.cpp.
References _first, ObjectLink::GetIndex(), ObjectLink::GetNext(), ObjectLink::GetValue(), ObjectLink::SetNext(), and ObjectLink::SetValue().
Referenced by Maze::AddRoom(), and Room::SetSide().
Member Data Documentation
class ObjectLink* ObjectArray::_first [private]
Definition at line 22 of file ObjectArray.h.
Referenced by FreeArray(), GetAt(), IsEmpty(), ObjectArray(), Print(), PutAt(), and ~ObjectArray().
The documentation for this class was generated from the following files:
ObjectArray.h
ObjectArray.cpp