Abstract Factory Design Pattern: global.h File Reference
global.h File Reference
#include <stdio.h>
Enumerations
enum Direction { North, South, East, West }
Functions
void PrintIndent (int indent)
Enumeration Type Documentation
enum Direction
Enumerator:
North
South
East
West
Definition at line 7 of file global.h.
Function Documentation
void PrintIndent (int indent)
Definition at line 5 of file global.cpp.
Referenced by Wall::Print(), Room::Print(), ObjectLink::Print(), ObjectArray::Print(), Object::Print(), MazeGame::Print(), MazeFactory::Print(), Maze::Print(), MapSite::Print(), Door::Print(), BombedWall::Print(), and BombedMazeFactory::Print().