Abstract Factory Design Pattern: global.cpp File Reference
global.cpp File Reference
#include "global.h"
Functions
void PrintIndent (int indent)
Function Documentation
void PrintIndent (int indent)
Definition at line 5 of file global.cpp.
Referenced by Wall::Print(), Room::Print(), ObjectLink::Print(), ObjectArray::Print(), Object::Print(), MazeGame::Print(), MazeFactory::Print(), Maze::Print(), MapSite::Print(), Door::Print(), BombedWall::Print(), and BombedMazeFactory::Print().