Abstract Factory Design Pattern: singleton.cpp File Reference
singleton.cpp File Reference
#include "Singleton.h"
#include "BombedMazeFactory.h"
#include "string.h"
Functions
class MazeFactory * FactoryInstance (bool bombed_)
class MazeFactory * FactoryInstance ()
Variables
class MazeFactory * factoryInstance
Function Documentation
class MazeFactory* FactoryInstance ()
Definition at line 22 of file singleton.cpp.
References FactoryInstance().
Referenced by FactoryInstance(), and main().
class MazeFactory* FactoryInstance (bool bombed_)
Definition at line 9 of file singleton.cpp.
References MazeFactory::MazeFactory().
Variable Documentation
class MazeFactory* factoryInstance
Definition at line 6 of file singleton.cpp.