Abstract Factory Design Pattern: MazeFactory.h File Reference
MazeFactory.h File Reference
#include "Object.h"
Classes
class MazeFactory
Functions
class MazeFactory * FactoryInstance ()
class MazeFactory * FactoryInstance (bool bombed_)
Function Documentation
class MazeFactory* FactoryInstance (bool bombed_)
Definition at line 9 of file singleton.cpp.
References MazeFactory::MazeFactory().
class MazeFactory* FactoryInstance ()
Definition at line 22 of file singleton.cpp.
Referenced by FactoryInstance(), and main().