Abstract Factory Design Pattern: ObjectLink Class Reference
ObjectLink Class Reference
#include <ObjectLink.h>
Inherits Object.
Public Member Functions
ObjectLink (int index, class Object *pOn)
virtual ~ObjectLink ()
class Object * GetValue ()
void SetValue (class Object *)
int GetIndex ()
void SetNext (class ObjectLink *pO)
class ObjectLink * GetNext ()
virtual void Print (int indent=0)
Private Attributes
class ObjectLink * _previous
class ObjectLink * _next
class Object * _value
int _index
Detailed Description
Definition at line 6 of file ObjectLink.h.
Constructor & Destructor Documentation
ObjectLink::ObjectLink (int index, class Object * pOn)
Definition at line 3 of file ObjectLink.cpp.
References _index, and _value.
ObjectLink::~ObjectLink () [virtual]
Definition at line 9 of file ObjectLink.cpp.
Member Function Documentation
int ObjectLink::GetIndex ()
Definition at line 30 of file ObjectLink.cpp.
References _index.
Referenced by ObjectArray::GetAt(), and ObjectArray::PutAt().
class ObjectLink * ObjectLink::GetNext ()
Definition at line 18 of file ObjectLink.cpp.
References _next.
Referenced by ObjectArray::FreeArray(), ObjectArray::GetAt(), ObjectArray::Print(), ObjectArray::PutAt(), and ObjectArray::~ObjectArray().
class Object * ObjectLink::GetValue ()
Definition at line 22 of file ObjectLink.cpp.
References _value.
Referenced by ObjectArray::FreeArray(), ObjectArray::GetAt(), ObjectArray::Print(), and ObjectArray::PutAt().
void ObjectLink::Print (int indent = 0) [virtual]
Reimplemented from Object.
Definition at line 34 of file ObjectLink.cpp.
References _index, _next, _previous, _value, Object::Print(), and PrintIndent().
void ObjectLink::SetNext (class ObjectLink * pO)
Definition at line 11 of file ObjectLink.cpp.
References _next, and _previous.
Referenced by ObjectArray::PutAt().
void ObjectLink::SetValue (class Object * o)
Definition at line 26 of file ObjectLink.cpp.
References _value.
Referenced by ObjectArray::PutAt().
Member Data Documentation
int ObjectLink::_index [private]
Definition at line 25 of file ObjectLink.h.
Referenced by GetIndex(), ObjectLink(), and Print().
class ObjectLink* ObjectLink::_next [private]
Definition at line 23 of file ObjectLink.h.
Referenced by GetNext(), Print(), and SetNext().
class ObjectLink* ObjectLink::_previous [private]
Definition at line 22 of file ObjectLink.h.
Referenced by Print(), and SetNext().
class Object* ObjectLink::_value [private]
Definition at line 24 of file ObjectLink.h.
Referenced by GetValue(), ObjectLink(), Print(), and SetValue().
The documentation for this class was generated from the following files:
ObjectLink.h
ObjectLink.cpp