Abstract Factory Design Pattern: MazeFactory Class Reference
MazeFactory Class Reference
#include <MazeFactory.h>
Inherits Object.
Inherited by BombedMazeFactory.
Public Member Functions
MazeFactory ()
virtual ~MazeFactory ()
virtual class Maze * MakeMaze () const
virtual class Wall * MakeWall () const
virtual class Room * MakeRoom (int n) const
virtual class Door * MakeDoor (class Room *r1, class Room *r2) const
virtual void Print (int indent=0)
Detailed Description
Definition at line 15 of file MazeFactory.h.
Constructor & Destructor Documentation
MazeFactory::MazeFactory ()
Definition at line 9 of file MazeFactory.cpp.
Referenced by FactoryInstance().
MazeFactory::~MazeFactory () [virtual]
Definition at line 11 of file MazeFactory.cpp.
Member Function Documentation
class Door * MazeFactory::MakeDoor (class Room * r1, class Room * r2) const [virtual]
Definition at line 25 of file MazeFactory.cpp.
References Door::Door().
Referenced by MazeGame::CreateMaze().
class Maze * MazeFactory::MakeMaze () const [virtual]
Definition at line 13 of file MazeFactory.cpp.
References Maze::Maze().
Referenced by MazeGame::CreateMaze().
class Room * MazeFactory::MakeRoom (int n) const [virtual]
Definition at line 21 of file MazeFactory.cpp.
References Room::Room().
Referenced by MazeGame::CreateMaze().
class Wall * MazeFactory::MakeWall () const [virtual]
Reimplemented in BombedMazeFactory.
Definition at line 17 of file MazeFactory.cpp.
References Wall::Wall().
Referenced by MazeGame::CreateMaze().
void MazeFactory::Print (int indent = 0) [virtual]
Reimplemented from Object.
Reimplemented in BombedMazeFactory.
Definition at line 29 of file MazeFactory.cpp.
References PrintIndent().
The documentation for this class was generated from the following files:
MazeFactory.h
MazeFactory.cpp